### ISSUE TITLE
Add Akka Cluster Sharding

### ISSUE THREAD

**Issue by calvinlfer** [binhnguyennus/awesome-scalability#19]
I think this should go under the Scalability topic for Akka:

> Cluster sharding is useful when you need to distribute actors across several nodes in the cluster and want to be able to interact with them using their logical identifier, but without having to care about their physical location in the cluster, which might also change over time.

See https://doc.akka.io/docs/akka/2.5/cluster-sharding.html

**Comment by binhnguyennus** [comment]
Dear @calvinlfer ,

Thank you very much for your sharing! However, I am sorry that I will not be able to add it due to three reasons:

1. It does not illustrate a real application/project from a tech company/tech team.
2. It is way too specific, so readers will just see the tree (Akka configuration) but not the forest (scalability, how it links to other components).
3. It does not make much sense to add a Help document in this repo.

If you have any additional concerns, please feel free to get in touch! Thank you and Happy Coding!

Best regards,
Bình.

**Comment by calvinlfer** [comment]
Ah okay, good point, sorry @binhnguyennus 
We used this at my previous company (LoyaltyOne) to implemented a distributed transaction processing system but we never officially published any articles, I guess that would have been more appropriate. I'll close this for now and come back with a real world use case (where it's used at a company)
